version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: neefl-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: neefl
      POSTGRES_USER: neefl
      POSTGRES_PASSWORD: neefl
    ports:
      - "5432:5432"
    volumes:
      - neefl_pg:/var/lib/postgresql/data

volumes:
  neefl_pg:
